name: Release to VSCode marketplace

on:
  create:
    tags:
      - v*

jobs:
  build:
    name: Publish
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Publish to Marketplace
        run: |
          mkdir -p -m 777 ~/.npm-global-packages
          npm config set prefix '~/.npm-global-packages'
          export PATH=~/.npm-global-packages/bin:$PATH
          npm ci
          npm install -g vsce
          vsce package
          vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
